### ISSUE TITLE
Createpackage fails with Object Reference not set errors

### ISSUE THREAD

**Issue by avinb** [silanis/esl.sdk.net#8]
Hi 

I just tried to run the GettingStartedExample on my development environment with SDK 10.10, I am getting Object Reference not set errors .  

Below is Code 

            var eslClient = new EslClient("key", "https://esign-live.dev.cse.mydomain.com/api");
            DocumentPackage superDuperPackage = PackageBuilder.NewPackageNamed("GettingStartedExample: " + DateTime.Now)
                .WithSettings(DocumentPackageSettingsBuilder.NewDocumentPackageSettings())
                    .WithSigner(SignerBuilder.NewSignerWithEmail(email1)
                                .WithFirstName("John1")
                                .WithLastName("Smith1")
                                .WithCustomId("SIGNER1"))
                    .WithDocument(DocumentBuilder.NewDocumentNamed(DOCUMENT_NAME)
                                .FromStream(fileStream1, DocumentType.PDF)
                                  .WithSignature(SignatureBuilder.SignatureFor(email1)
                                   .OnPage(0)
                                   .AtPosition(100, 100))
                                  .WithSignature(SignatureBuilder.InitialsFor(email1)
                                   .OnPage(0)
                                   .AtPosition(100, 200))
                                  .WithSignature(SignatureBuilder.CaptureFor(email1)
                                   .OnPage(0)
                                   .AtPosition(100, 300))
                                  )
            .Build();
            superDuperPackage.Settings.OptOutReasons.Add("Dont agree to it");
            superDuperPackage.Settings.OptOutReasons.Add("Dont agree to pricing");

            superDuperPackage.Settings.DeclineReasons.Add("Dont agree to it");
            superDuperPackage.Settings.DeclineReasons.Add("Dont agree to pricing");
            superDuperPackage.Settings.ShowDownloadButton = false;
            superDuperPackage.Settings.EnableDecline = false;

    var packageId = eslClient.CreatePackage(superDuperPackage);

Above line fails. 

            eslClient.SendPackage(packageId);
            // Optionally, get the session token for integrated signing.
            SessionToken sessionToken = eslClient.SessionService.CreateSessionToken(packageId, "SIGNER1");

Below is the Error 

            Silanis.ESL.SDK.EslException was unhandled
              Message=Could not create a new package. Exception: Object reference not set to an instance of an object.
            Source=Silanis.ESL
              StackTrace:
                   at Silanis.ESL.SDK.Services.PackageService.CreatePackage(Package package)
                   at Silanis.ESL.SDK.EslClient.CreatePackage(DocumentPackage package)
                   at Esign_LivePOC.GettingStartedExample.Execute()
                   at Esign_LivePOC.GettingStartedExample.Main(String[] args)
                   at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
                   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
                   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
                   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
                   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                   at System.Threading.ThreadHelper.ThreadStart()
              InnerException: System.NullReferenceException
                   Message=Object reference not set to an instance of an object.
                   Source=Silanis.ESL
                   StackTrace:
                        at Silanis.ESL.SDK.Internal.HttpMethods.PostHttp(String apiToken, String path, Byte[] content)
                        at Silanis.ESL.SDK.RestClient.Post(String path, String jsonPayload)
                        at Silanis.ESL.SDK.Services.PackageService.CreatePackage(Package package)
       InnerException: 

Any pointers to resolve this ?

thanks
Avinash

**Comment by ehardy** [comment]
Hi Avinash,

We will look into this issue and get back to you as soon as possible.

Regards,

Etienne

**Comment by ehardy** [comment]
Hi Avinash,

We just noticed that the URL you have specified in your example (
https://esign-live.dev.cse.mydomain.com/api) is not a URL that we support.
If you have opened a Sandbox account and got your API key, I suggest you
try your sample against https://sandbox.e-signlive.com/api. Also, don't
forget to pass a valid API key to the EslClient constructor.

Hope that helps.

Etienne

**Comment by avinb** [comment]
Hi Etienne, 

I have got a on-premise installation of Esign-Live, against which we intend to use .NET SDK. is that an issue ?

thanks

**Comment by ehardy** [comment]
No it should not be an issue. What version of e-SignLive do you have
installed? Also, could you let me know if you had anyone of the Silanis
Professional Services team help you with the installation, what is your
company name, those kinds of details. It will help get a bit of background.

Thanks

Etienne

**Comment by avinb** [comment]
This is 10.9.37 version , Joshua Varga has been our professional contact from your side. ORG name GE

**Comment by avinb** [comment]
Please close the case .
